### ISSUE TITLE
'reopened issue' does not display issue icon

### ISSUE THREAD

**Issue by devdrops** [devspace/devspace-user-requests#102]
The issue card has an icon with an exclamation point, but the card with a reopened issue doesn't have any icon at all :cry:.

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1259313/17760293/3041fcba-64d5-11e6-9942-2235806001ce.png)

Notice the issue icon found on the first card (from top to bottom), and then the lack of icon on a card from an equivalent subject (the 5th from top to bottom).

**Comment by zenorocha** [comment]
Ohh, thanks @devdrops for reporting!

**Comment by zenorocha** [comment]
This issue is finally fix, sorry for taking so long to reply @devdrops.

**Comment by devdrops** [comment]
No problemo :)
