### ISSUE TITLE
Make this project open source

### ISSUE THREAD

**Issue by abiduzz420** [devspace/devspace-user-requests#112]
I would like to contribute to this project as I find it really helpful to track different open source projects. Since this project is built in React, I shall be able to contribute to it. 

Please make the code open source, so that this project could further grow and become a must have tool for any one who's doing open source contributions. 

Also comment on the issue if you feel the same as a sign of support. Thanks!

**Comment by zenorocha** [comment]
Hey @abiduzz420,

Thanks for starting this conversation. I like the idea to make this open source, but before I do it I want to make sure there are people committed to making it better. Are you willing to help and maintain it?

Thanks!

**Comment by abiduzz420** [comment]
I would be very happy to help this project grow. There are many feature requests in the issues and each one of us can pick an issue and start contributing in the form of discussions, code, writing tests and documentation. 
I am willing to help and maintain the project @zenorocha :)
Cheers!

**Comment by zenorocha** [comment]
In that case, here it is: https://github.com/devspace/devspace

**Comment by abiduzz420** [comment]
Thanks a lot! :1st_place_medal: :tada:
