### ISSUE TITLE
Desktop APP - Copy/paste doesn't work on input fields

### ISSUE THREAD

**Issue by heldr** [devspace/devspace-user-requests#15]
Try to login pasting a password or create a new tab pasting a user profile.

**Comment by zenorocha** [comment]
Thanks for reporting @heldr!

**Comment by obetomuniz** [comment]
Doesn't work on item content too.

**Comment by zenorocha** [comment]
Fixed on [1.0.0-alpha.1](https://github.com/devspace/devspace/releases/download/1.0.0-alpha.1/DevSpace-OSX.zip)!

/cc @henriquebastos

**Comment by heldr** [comment]
:tea:
