### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by obetomuniz** [devspace/devspace-user-requests#16]
- Create issues in-app using the GH API
- Add title (when hover the icon) to each item inside the column. i.e.: Star, Comment, Fork, etc.
- Create Columns by Group. i.e.: Organizations Group Users Group, Repositories Group, etc.
- Allow notifications like the TweetDeck options (Desktop Notification, Sounds, etc.)
  - Notify new version (like Spotify)
  - Notify new column item
- Allow font resize
- Allow create a column with custom term of search
- Enable analysis for all user behaviors (i.e.: Type of column added, column removed, etc.)
- Enable

**Comment by zenorocha** [comment]
- Create issues in-app using the GH API

Creating issues is just one feature between a huge number of possible actions that could be done inside the app. You could star a repo, quick comment on a issue, and many many more. As soon as we finish a good workflow regarding consuming information, we can move to actually performing actions.
- Add title (when hover the icon) to each item inside the column. i.e.: Star, Comment, Fork, etc.

I don't think that's necessary. That icon is just a quick representation of what that event is describing.
- Create Columns by Group. i.e.: Organizations Group Users Group, Repositories Group, etc.

That's a pretty good idea. We should move discussion to a separate issue.
- Allow notifications like the TweetDeck options (Desktop Notification, Sounds, etc.)

That's a pretty good idea. We should move discussion to a separate issue.
- Notify new version (like Spotify)

Sure, auto updates will be handled before we go public.
- Notify new column item

Duplicated from #5
- Allow font resize

Cool. This could be a global app settings in the future.
- Allow create a column with custom term of search

Search is one of the new types of columns that needs to be added.
- Enable analysis for all user behaviors (i.e.: Type of column added, column removed, etc.)

Analytics is a very nice idea but it's very very far from being included in the roadmap. The idea now is to make a very stable product before introducing those kinds of new features.
