### ISSUE TITLE
Request repo permission scope in order to get private events

### ISSUE THREAD

**Issue by zenorocha** [devspace/devspace-user-requests#2]

**Comment by lucianosousa** [comment]
:+1:

**Comment by obetomuniz** [comment]
:+1:

**Comment by luanmuniz** [comment]
:+1:

**Comment by zenorocha** [comment]
@lucianosousa @obetomuniz @luanmuniz can you confirm that only organizations are not showing private events?

**Comment by luanmuniz** [comment]
@zenorocha Yes. Organizations don't show events from private repositories.

**Comment by obetomuniz** [comment]
@zenorocha Yes. Organizations don't show private events, just for public repositories.

**Comment by zenorocha** [comment]
Perfect. Renaming this issue...

**Comment by luanmuniz** [comment]
@zenorocha Private repositories don't work either and the feed for users don't show private events as well.

**Comment by zenorocha** [comment]
That's right, thanks @luanmuniz!

**Comment by zenorocha** [comment]
As of [v1.0.0-alpha.4](https://github.com/devspace/devspace/releases/tag/v1.0.0-alpha.4), DevSpace now shows private events for Home, User, and Repository columns.

Organization column still need to be done #23.

> P.S.: This updates requires a new login.

**Comment by luanmuniz** [comment]
Yes! :100:

**Comment by zenorocha** [comment]
Now available for Organizations too!

P.S.: You need to create a new column for this to work ;)
