### ISSUE TITLE
After closing, window don't show up again

### ISSUE THREAD

**Issue by luanmuniz** [devspace/devspace-user-requests#20]
In the Mac app, if i click on the close button the app close and it don't open again when i click on the icon at the Dock. I need to quit the app and open it again.
The application is open but i cant see the window.

**Comment by obetomuniz** [comment]
:+1:

**Comment by zenorocha** [comment]
Fixed on [v1.0.0-alpha.3](https://github.com/devspace/devspace/releases/tag/v1.0.0-alpha.3)!
