### ISSUE TITLE
Issues comments

### ISSUE THREAD

**Issue by jaydson** [devspace/devspace-user-requests#25]
It would be so nice if issues comments were available on devspace interface.
I mean, not just the info that someone has commented.
Perhaps something like Tweetdeck does:
![screenshot from 2015-12-23 19 15 28](https://cloud.githubusercontent.com/assets/72206/11985215/94bfc8f8-a9a9-11e5-93dd-6d80721db8bc.png)

**Comment by zenorocha** [comment]
Closing this and merging it to #24 so we can keep things cleaner over here ;)
