### ISSUE TITLE
Github user profile box

### ISSUE THREAD

**Issue by jaydson** [devspace/devspace-user-requests#26]
Again, like Tweetdeck, it would be cool having a user profile box:  
![screenshot from 2015-12-23 19 35 04](https://cloud.githubusercontent.com/assets/72206/11985484/67d758b2-a9ac-11e5-9d79-51791461ef02.png)

We can have all user info on this box, like popular repos, maybe graphs, last starred repos, etc.

**Comment by obetomuniz** [comment]
:+1:

**Comment by zenorocha** [comment]
Closing this and merging it to #24 so we can keep things cleaner over here ;)
