### ISSUE TITLE
Cannot request to join private beta

### ISSUE THREAD

**Issue by felipecsl** [devspace/devspace-user-requests#31]
![screen shot 2016-01-13 at 12 22 10 am](https://cloud.githubusercontent.com/assets/190648/12288739/b585b2b8-b98b-11e5-9d05-aafa07ab5083.png)

**Comment by theus** [comment]
Same with me. :/

**Comment by zenorocha** [comment]
Could you try now?

**Comment by zenorocha** [comment]
Sorry about that :/

**Comment by theus** [comment]
It's all right!
