### ISSUE TITLE
Optimize mobile experience

### ISSUE THREAD

**Issue by xdumaine** [devspace/devspace-user-requests#35]
Added a few columns but couldn't see them on iPhone or iPad since the app wouldn't scroll horizontally

**Comment by zenorocha** [comment]
The app is not optimized for mobile yet but hopefully we'll be able to fix this in the future. Thanks @xdumaine ;)

**Comment by zenorocha** [comment]
Fixed! Could you take a look now @xdumaine?

**Comment by xdumaine** [comment]
Looks better! Adding apple-mobile-web-app-capable meta tag would be cool so
it could be opened in web app style on iPhone.

**Comment by zenorocha** [comment]
I did that already ;)
