### ISSUE TITLE
Show the branch commits were pushed to

### ISSUE THREAD

**Issue by mhinze** [devspace/devspace-user-requests#39]
`[user](user link) pushed [n commits](compare link) to [org/repo](repo link)`

:arrow_right: 

`[user](user link) pushed [n commits](compare link) to [org/repo:branch](:repo/tree/:branch link)`

**Comment by zenorocha** [comment]
Done! Thanks for your suggestion @mhinze ;D

**Comment by mhinze** [comment]
Awesome! Thanks.
