### ISSUE TITLE
Issues and PRs count

### ISSUE THREAD

**Issue by rafaelrinaldi** [devspace/devspace-user-requests#41]
A killer feature would be to have a quick way to see how many PRs and Issues are open for a given repository. The default GitHub notification icon is not reliable and is even misleading if you ask me.

What I use today as a workaround is this little Chrome extension called [`gh-nag`](https://github.com/jamestalmage/gh-nag) by @jamestalmage.

In DevSpace I think this can be displayed on the repository title:

![devspace-issues-count](https://cldup.com/OoncxYMSjB-3000x3000.png)

Thanks and keep the great work!

**Comment by zenorocha** [comment]
Hey @rafaelrinaldi! It took a while but this feature is finally here. The implementation is a little bit different than you suggested but I think you're gonna like it ;)

![Preview](https://cloud.githubusercontent.com/assets/398893/15801066/d0cf28dc-2a3e-11e6-96d8-1fd0184e21b4.png)

**Comment by rafaelrinaldi** [comment]
@zenorocha You nailed it 👌

**Comment by zenorocha** [comment]
🎉
