### ISSUE TITLE
Use regex for filters

### ISSUE THREAD

**Issue by rafaelrinaldi** [devspace/devspace-user-requests#42]
Istead of a whitelist and a blacklist I think that using pattern matching via regex would be way better. This software is for developers anyway :neckbeard:
By doing this, the fields "Matching" and "Excluding" could be replaced by a single "Pattern" field in the "Filter events" modal.

Would also be nice to toggle patterns that you previously setup. That way one can easily compose even complex filters in the :wink: of an :eyes:
The presets can live on the filters modal since there's plenty of space now :+1: 

Thanks and keep the great work!

**Comment by zenorocha** [comment]
Awesome, I love this idea.

Although `Pattern` is way more powerful than `Matching` and `Excluding`, I think it's a good idea to keep them for beginners who are not familiar with regex yet.

**Comment by zenorocha** [comment]
Done!

<img width="413" alt="screen shot 2016-02-09 at 10 26 14 am" src="https://cloud.githubusercontent.com/assets/398893/12926503/8da6dd10-cf18-11e5-871e-1fab5deaaf03.png">

Let me know what you think ;D

**Comment by rafaelrinaldi** [comment]
![hell yes](https://cldup.com/BWQWlBg-zK.gif)
