### ISSUE TITLE
Save removed columns

### ISSUE THREAD

**Issue by montogeek** [devspace/devspace-user-requests#45]
Hi!

It would be great to get a list of saved columns, currently when you close a column, is deleted forever

**Comment by zenorocha** [comment]
Hey @montogeek,

I don't think I completely understand what you're suggesting. Could you elaborate a little bit more? Why would you want to see the list of columns you deleted?

**Comment by montogeek** [comment]
Hi @zenorocha 
Maybe you deleted it because you do not want to see more notifications from the user/repo/organization, but later, in the future, you want to get those notifications again, so, instead of have to remember it and add the column again, you can simply choose it from the list

**Comment by zenorocha** [comment]
Got it. I'll close this one for now since there are other issues with higher priorities now. But thanks for sharing your ideas @montogeek ;)

**Comment by montogeek** [comment]
Thank you for hearing!
