### ISSUE TITLE
Update notice

### ISSUE THREAD

**Issue by fdaciuk** [devspace/devspace-user-requests#55]
I don't know if Devspace already has this feature, but would be nice if we can see when it there is an update, like:

![selection_140](https://cloud.githubusercontent.com/assets/487669/12979781/63c7287a-d0c0-11e5-9275-3a3c88ba243f.png)

**Comment by zenorocha** [comment]
DevDocs does that because it has offline support. At this moment, we don't have something like that, but it's probably a good idea since many users will just pin the tab.

**Comment by fdaciuk** [comment]
For sure! :dancer: :dancer: :sparkles:

**Comment by zenorocha** [comment]
Done in [v1.0.0-beta.8](https://github.com/devspace/devspace/releases/tag/v1.0.0-beta.8) ;)

![](https://cloud.githubusercontent.com/assets/398893/17038228/92fa1d2a-4f49-11e6-9983-27955b53cf9a.png)

Thanks @fdaciuk :)
