### ISSUE TITLE
Problem on The Login page on screen with height lower than 740

### ISSUE THREAD

**Issue by HenriqueLimas** [devspace/devspace-user-requests#57]
In the Login page on landscape mode on phones, tablets or notebook with height lower than 740 (like Samsung Chromebook) is not possible to access the footer links and in small screens like phones is not possible to see the login button.

**Comment by zenorocha** [comment]
+1 thanks for reporting @HenriqueLimas!

**Comment by zenorocha** [comment]
Fixed! Thanks @HenriqueLimas ;)
