### ISSUE TITLE
make Repository Columns easier to add

### ISSUE THREAD

**Issue by gauntface** [devspace/devspace-user-requests#58]
Would love a UI to select repositories I own / have attached to my account would be awesome rather than typing out username / repo.

**Comment by zenorocha** [comment]
Would #62 be a good solution for this?

**Comment by gauntface** [comment]
Its related but #62 sounds like repos related to user actions I was talking
about my own repos or repos of orgs I'm a part of, but mark as duplicate if
you feel it would cover both suggestions.

**Comment by zenorocha** [comment]
Got it!
