### ISSUE TITLE
Add ability to column width and font size, etc

### ISSUE THREAD

**Issue by zenorocha** [devspace/devspace-user-requests#6]
Include a default light theme and the possibility to create a custom theme

**Comment by damianh** [comment]
Would also like to add ability to set font size and use column width. My DevSpace vs Tweetdeck:

![image](https://cloud.githubusercontent.com/assets/57436/12972264/ef77d878-d0a3-11e5-9f4f-441e4e4a16b8.png)

**Comment by zenorocha** [comment]
+1 @damianh

**Comment by AdrianoCahete** [comment]
+1

**Comment by TimvdLippe** [comment]
For big screens, the column width is very small. It would be nice if it could flex, or at least be improved. :+1: for me!

**Comment by zenorocha** [comment]
Done! Check it out and let me know what you think ;D
