### ISSUE TITLE
Smaller Columns

### ISSUE THREAD

**Issue by hhsnopek** [devspace/devspace-user-requests#61]
I wanna be able to see more on my screen, right now I can only see 4 columns. On tweetdeck I am able to see 5. Maybe a compact mode would do

**Comment by AdrianoCahete** [comment]
Not smaller, but resizable columns. 'Cause it's a personal option. I like larger columns, f.e.

**Comment by hhsnopek** [comment]
yeah I was thinking something along the lines of compact, cozy & comfort modes like gmail

**Comment by zenorocha** [comment]
Yes, that would be great.

> Closing since it's duplicated from #6

**Comment by hhsnopek** [comment]
:+1:
