### ISSUE TITLE
missing documentation with examples on how to use

### ISSUE THREAD

**Issue by vasco3** [devspace/devspace-user-requests#63]

**Comment by zenorocha** [comment]
What kind of examples would you like to see?

**Comment by vasco3** [comment]
An example of how to use matching, excluding, regex for:
- filtering out only changes to a specific repo's CHANGELOG.md or HISTORY.md 
- filtering issues per label eg. https://github.com/zenorocha/ama/labels/english

**Comment by zenorocha** [comment]
Got it. Unfortunately filters do not work this way. It's only a string filter based on what GitHub's Events API  return.

My plan is to write some blogposts to explain the power of filters. Do you think that would help?

Thanks @vasco3!
