### ISSUE TITLE
Ability to add specific column by user actions

### ISSUE THREAD

**Issue by AdrianoCahete** [devspace/devspace-user-requests#66]
When i say "specific column" i mean columns like starred/forked repos from an user, push/PR's from user, created new repos, make repo public, comment and open issues.
From UI perspective, add a second screen before click User (from Add Column).

DevSpace already have and know that info (we can see by icons), you just can make possible to filter when add a new column.

It's like a column with a default filter for doing what you want.

**Comment by zenorocha** [comment]
Filters are advanced settings for columns. Adding another step on column creation would only make more confusing in terms of UX.

I prefer keeping the column creation workflow as easy as possible for now and if somebody wants a more advanced settings they can just set a filter.

I hope I understood you correctly. Thanks for sharing ideas with us ;D

**Comment by AdrianoCahete** [comment]
Sort of.
Is something like filters, but with a default filter already applied. You will be facilitating (idk if it's a correct term) user actions, in fact it's a better UX action.

If not a new panel, a set of pre created filters would be good.

**Comment by zenorocha** [comment]
What kind of pre created filters would you like to see? We can improve the placeholders with your ideas.
