### ISSUE TITLE
Links for new commits in a branch are broken

### ISSUE THREAD

**Issue by devdrops** [devspace/devspace-user-requests#67]
Noticed right now that in some links for branches (when you receive a notification of an update, like a new commit has been pushed, in a given branch), some specific words present on the branch name itself are not present in the link, which produces a broken link.

**Example**:
<img width="312" alt="captura de tela 2016-02-16 as 17 15 11" src="https://cloud.githubusercontent.com/assets/1259313/13087840/e524d854-d4d0-11e5-9c0a-6f00841b3840.png">
This is an update of a new commit into the branch `feature/ABC-1234`, which link should point to https://github.com/devdrops/the-naked-bundle/tree/feature/ABC-1234 (see first update). However, the link in the app is actually https://github.com/devdrops/the-naked-bundle/tree/ABC-1234, leading to a 404 page.

**Comment by zenorocha** [comment]
Fixed! Thanks a lot for reporting @devdrops ;)

**Comment by devdrops** [comment]
Awesome!

![wh00t](https://cloud.githubusercontent.com/assets/1259313/13095959/bc17de4e-d4fc-11e5-972d-efac105520f5.png)

**Comment by zenorocha** [comment]
lol
