### ISSUE TITLE
Access buttons unclear

### ISSUE THREAD

**Issue by TimvdLippe** [devspace/devspace-user-requests#74]
It might have been me, but when opening the site seeing two buttons regarding access, I was a little bit confused. Eventually I chose the "Public Access" and got redirected to GitHub. Only then did I understood it meant asking permission for private repositories or not.

In my case to make it a bit more obvious, a small header could be added with "Authenticate the application with GitHub". This would inform the user what the application is trying to do, as I was quite hesitant at first whether I should proceed and in which manner.

**Comment by zenorocha** [comment]
Done! Thanks for sharing your feedback Tim ;)
