### ISSUE TITLE
Show actual comment (on click)

### ISSUE THREAD

**Issue by TimvdLippe** [devspace/devspace-user-requests#75]
![image](https://cloud.githubusercontent.com/assets/5948271/13227359/86f03736-d996-11e5-9544-7b844352c2fb.png)

It would be nice to directly see the actual comment. Either on user interaction (on click) or in-line and truncated.

P.S. This would also be applicable for titles of new issues/pull requests

**Comment by zenorocha** [comment]
+1

> Closing since its duplicated from #40

**Comment by TimvdLippe** [comment]
Ah sorry I searched the repository but couldn't find the ticket.

**Comment by kidwm** [comment]
@zenorocha I'm here again, please don't put comment content as _more info in tooltips_.
