### ISSUE TITLE
Issue Title Display

### ISSUE THREAD

**Issue by asotog** [devspace/devspace-user-requests#76]
Might be helpful at least from user perspective to see the title of the issue, not just the issue number, a tooltip or something not too big showing the title, maybe hovering over the issue number and display the tooltip with the title, for example twitter when user is tagged, it shows up a bubble with some info related

**Comment by zenorocha** [comment]
+1

> Duplicated from #40

**Comment by kidwm** [comment]
@zenorocha Sorry, I don't think this is duplicated from that.

And I also want issue title to be displayed directly in the content block instead of a tooltip.
