### ISSUE TITLE
Only show scrollbar when needed

### ISSUE THREAD

**Issue by AdrianoCahete** [devspace/devspace-user-requests#80]
When column don't have all height, scroll dind't need to appears.

So `column-content` class needs to be `overflow-y` with `auto` instead of `scroll`

Before (actual):
![scroll_before](https://cloud.githubusercontent.com/assets/37474/13649425/57c1dacc-e61c-11e5-958f-0d1c3354b715.PNG)

After:
![scroll_after](https://cloud.githubusercontent.com/assets/37474/13649428/5c84be1c-e61c-11e5-9bbb-2ac08a15d5a5.PNG)

**Comment by zenorocha** [comment]
Done! Thanks for reporting @AdrianoCahete ;)
