### ISSUE TITLE
`⌘+,` to open settings panel

### ISSUE THREAD

**Issue by rafaelrinaldi** [devspace/devspace-user-requests#81]
As an OSX user, my muscle memory always go with <kbd>⌘</kbd>+<kbd>,</kbd> (command plus comma) to access the settings panel of any application. It would be nice to have this same behavior in DevSpace.

**Comment by zenorocha** [comment]
Thanks for your suggestion @rafaelrinaldi!

> Closing since it's duplicated from #13
