### ISSUE TITLE
Column scrolling down

### ISSUE THREAD

**Issue by cesards** [devspace/devspace-user-requests#84]
A column doesn't support down scrolling, so I can barely see what's going on!

Thank you for your work, by the way!

**Comment by zenorocha** [comment]
Hey @cesards, could you provide more info like a screenshot or something? I haven't seen other users with this kind of error yet.

**Comment by zenorocha** [comment]
Closing since it wasn't able to reproduce.

**Comment by cesards** [comment]
Sure!! Here you are :)   @zenorocha 

https://youtu.be/JQtGn946MFw

PS: You closed this too fast man!

**Comment by zenorocha** [comment]
Ohhhh, so you're trying to say that you want #3
