### ISSUE TITLE
Disallow duplicated columns

### ISSUE THREAD

**Issue by ftonato** [devspace/devspace-user-requests#87]
Disallow duplicated columns for _Users_, _Repositories_ and _Organizations_.

e.g.
![columns](https://cloud.githubusercontent.com/assets/5417662/13827733/e6c9dfa0-eb9c-11e5-963b-d6bffdb07e68.png)

**Comment by zenorocha** [comment]
Thanks for sharing but I don't agree @ftonato. You could have two columns with two different filters.

**Comment by ftonato** [comment]
Sorry @zenorocha, I've forgotten that there were filters.
