### ISSUE TITLE
Add two factors authentication

### ISSUE THREAD

**Issue by PierrickGT** [devspace/devspace-user-requests#88]
I've successfully logged in using the Private Access button but it didn't ask me for the two factors authentification code.
I was then unable to see my private repo.

Here is a GIF explaining the problem better than me.
![devspace](https://cloud.githubusercontent.com/assets/2401738/13876416/60e08286-ed04-11e5-867a-f86d2c5a692e.gif)

**Comment by zenorocha** [comment]
That's pretty weird. Could you try logging out, revoking access from DevSpace on GitHub (https://github.com/settings/applications), and then logging again with private access?
