### ISSUE TITLE
Glitch on the fonts change them from Patua One and Roboto for ComicSans

### ISSUE THREAD

**Issue by Wmitrut** [devspace/devspace-user-requests#95]
Well, I was in Windows, Chrome 50.0.2661.75 with a 5mb connection and I experienced some type of glitch when I tried to log in Devspace... when I opened the landing page, the main fonts was replaced by ComicSans, can someone explain to me why that can happen? 

![captura de tela 2016-04-19 11 05 57](https://cloud.githubusercontent.com/assets/5539257/14642330/72efb098-0620-11e6-9870-bdbcd6a2fb77.png)

**Comment by zenorocha** [comment]
It seems like `cursive` (which is the fallback for our webfont) is not available on windows. I just changed it to be arial so this should be fixed now ;)

Thanks for reporting @Wmitrut!
