### ISSUE TITLE
List all watched repositories on github

### ISSUE THREAD

**Issue by mauricionr** [devspace/devspace-user-requests#99]
Could be nice also see all watching repositories on devspace,

And when remove them from devspace, the app also remove from watching list on github.

got it?

Thankss! :smile:

**Comment by zenorocha** [comment]
Hey @mauricionr, thanks for your suggestion. The `Home` column already shows activities from all watching repositories. But unfortunately there's no way to unwatch a repository right now. We hope to add more in-app actions like Star/Unstar, Fork and Watch/Unwatch in the future #24.

**Comment by mauricionr** [comment]
@zenorocha i mean 

see the follwing image

![image](https://cloud.githubusercontent.com/assets/2263551/17041857/81ee93ea-4f7f-11e6-88d3-b1ef7f7d0f92.png)

Thanks!

**Comment by zenorocha** [comment]
I see, this could be nice once we have a UI for Notifications.
